### ISSUE TITLE
下载你发布的版本，就那个单文件的exe，运行就闪退。

### ISSUE THREAD

**Issue by windofuo** [YYuX-1145/Srt-AI-Voice-Assistant#19]
显卡3070 8G的，cosyvoice使用没问题。

**Comment by YYuX-1145** [comment]
尝试使用命令行启动它，然后截取报错内容。

**Comment by windofuo** [comment]
![image](https://github.com/user-attachments/assets/d6fed5ff-2006-4944-aa67-f98ebe6bb4c9)

**Comment by windofuo** [comment]
我又下了源码版本的，依赖也下载好了，配置好后也能正常启动gpt-sovits v2的接口服务，但是在转换字幕文件到音频时，最后一条字幕转换完成后（应该是到了合并音频）的时候，就出错了。
gpt-sovits v2的提示是这样的：
![image](https://github.com/user-attachments/assets/79892d3a-75f4-413b-a21c-4b006a36bf45)

大佬你打的软件提示是这样的：
![image](https://github.com/user-attachments/assets/187a71e9-7fc2-4873-8676-dbd6faa05937)

**Comment by YYuX-1145** [comment]
1.非常抱歉，打包版的代码落后于代码版，确实存在此问题，之后会重新打包新版本的代码。
2.你用的不是官方版的整合包？

**Comment by windofuo** [comment]
> 1.非常抱歉，打包版的代码落后于代码版，确实存在此问题，之后会重新打包新版本的代码。（现已重新上传打包版） 2.你用的不是官方版的整合包？

首先非常感谢你的答复。我用的就是从你这里下载的。

**Comment by YYuX-1145** [comment]
我指的是GSV整合包，只支持花佬官方发布的

**Comment by windofuo** [comment]
用最新发布的exe单文件那个就下面的提示：
![image](https://github.com/user-attachments/assets/523b986c-449e-4af4-b5e9-e998d67f409c)
还有你说的花佬发的那个能给个链接嘛？

**Comment by windofuo** [comment]
是这个嘛？
![Uploading image.png…]()

**Comment by YYuX-1145** [comment]
HF上的没看过，b站上是有的。或者拉一下官方仓库的主分支最新代码也是一样的

**Comment by windofuo** [comment]
> HF上的没看过，b站上是有的。或者拉一下官方仓库的主分支最新代码也是一样的

好的，非常感谢，我去搞下来了，等会儿试试看。

**Comment by windofuo** [comment]
试了，还是不行，下了原版gvs整合包，但是还是老问题，在你的软件里配置好，点切换模型都没问题，gvs有正常响应，但是点生成就出错了，
![image](https://github.com/user-attachments/assets/518cbe82-e293-4f1e-b95c-65599aa8ea4e)
![image](https://github.com/user-attachments/assets/2ebd896f-9bf3-4524-a121-d81deb00bd6f)

**Comment by YYuX-1145** [comment]
你用的不是api_v2?

**Comment by windofuo** [comment]
我是在你的程序里直接启动GVS的，不清楚是哪个，有区别？

**Comment by YYuX-1145** [comment]
预设你看不见？视频有介绍啊

我不知道你用的哪一版代码，GPT-SoVITS0821貌似不支持辅助参考音频所以可能会产生兼容问题，但是你从官方仓库主分支里拉的代码一定是没问题的

有人产生404报错就是因为用了某个日更up的整合包，因为他对接口进行了意义不明的修改

**Comment by windofuo** [comment]
> 预设你看不见？视频有介绍啊
> 
> 我不知道你用的哪一版代码，GPT-SoVITS0821貌似不支持辅助参考音频所以可能会产生兼容问题，但是你从官方仓库主分支里拉的代码一定是没问题的
> 
> 有人产生404报错就是因为用了某个日更up的整合包，因为他对接口进行了意义不明的修改

不好意思，我没弄明白那个预设什么意思，抱歉，哈哈。
刚才我加了辅助语音，它开始转换了，但是结束的时候提示因为语音和SRT的时间戳对不上，所以没能合成完整的音频。但是从这以后又歇火了，再点击生成就不不工作了，我重新启动了gvs的接口服务也不行。我把你这个程序重新启动一下再看看。

![image](https://github.com/user-attachments/assets/7194ee89-0477-4943-a3d2-e60f458e0a30)

**Comment by windofuo** [comment]
再点击生成就不工作了。奇怪了，一摸一样的配置和操作步骤，你的程序提示是这样的：
![image](https://github.com/user-attachments/assets/114d963d-eca7-4348-b108-14f9efad77ae)
![image](https://github.com/user-attachments/assets/f23e93ae-f4e0-476b-bbec-d8d4d1df754f)

太奇怪了，刚才我从外回家一开机就开始搞，结果第一次是有动作的，和gvs通讯也是可以的，就是最后合成的时候出了点问题，那个也不是你程序的问题，但是自从这之后，就完全罢工了，哈哈。

**Comment by YYuX-1145** [comment]
![image](https://github.com/user-attachments/assets/930aab1c-74b5-4640-8824-778e3c098a19)
也许这种情况会导致此问题，现在传了一个修复

**Comment by windofuo** [comment]
我刚才找到一个原因，就是把字幕中间的空行都删除了，点了生成它有反应了，也给gvs传递数据了，但是又返回一个错误，哈哈。如下：
![image](https://github.com/user-attachments/assets/f00f3ca3-5cb6-4908-8709-2ca00113f59d)
我傻眼了。

**Comment by windofuo** [comment]
不对，好像向gvs推送时也有问题：
![image](https://github.com/user-attachments/assets/56108378-1dbc-44a2-ab27-ecc8b87cfeef)

**Comment by YYuX-1145** [comment]
空行属于文件标准，GSV报错多半是因为接收了非法的字符串导致请求无法解析，在不了解文件内容的情况下还请您不要随意修改其他软件导出的字幕

**Comment by windofuo** [comment]
> 空行属于文件标准，GSV报错多半是因为接收了非法的字符串导致请求无法解析，在不了解文件内容的情况下还请您不要随意修改其他软件导出的字幕

谢谢提示，感谢你的耐心。我刚才试了一下OK了，看来之前多半是字幕的问题。
