### ISSUE TITLE
中英混合的字幕，英文单词都自动跳过了

### ISSUE THREAD

**Issue by Hellas51** [YYuX-1145/Srt-AI-Voice-Assistant#3]
用于GPT和VoITs模型训练的音频源是纯中文的，请问这和英文单词，如Python/Java等等常见专业术语自动跳过有关系吗？谢谢！

**Comment by YYuX-1145** [comment]
GSV的api暂不支持混读，bv2是支持的，语言选择auto

**Comment by YYuX-1145** [comment]
GSV的api暂不支持混读，bv2是支持的，语言选择auto
