### ISSUE TITLE
API无法启动？

### ISSUE THREAD

**Issue by josh9019** [YYuX-1145/Srt-AI-Voice-Assistant#7]
![QQ截图20240327140612](https://github.com/YYuX-1145/Srt-AI-Voice-Assistant/assets/129022376/35c1c043-694c-4da4-a628-0863a6a2c6e4)
这个提示是没有指定模型的意思吗？怎么解决呢？

**Comment by YYuX-1145** [comment]
非fast-inference分支用户请勿下载测试版本
