### ISSUE TITLE
GPT-SoVITS切换模型发生错误。

### ISSUE THREAD

**Issue by joneb998** [YYuX-1145/Srt-AI-Voice-Assistant#8]
GPT-SoVITS切换模型发生错误。报错内容: 404 Client Error: Not Found for url: http://127.0.0.1:9683/set_gpt_weights?weights_path=E:%5CProgram%20Files%5CGPT-SoVITS-beta0306fix2%5CGPT_weights%5Cxingzou-e15.ckpt

点击切换模型后一直出现这个报错提示，尝试换了port，重新训练模型等等办法都不行，请问如何解决
![微信截图_20240412142623](https://github.com/YYuX-1145/Srt-AI-Voice-Assistant/assets/166279515/00855c2a-ae11-4d9d-b1c5-5a7fdd292327)

**Comment by YYuX-1145** [comment]
请看左上角，并确保api已经更新
